name: Telegram Notify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Changed Files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            commits=$(echo '${{ toJson(github.event.commits) }}' | jq -r '.[].id')
            files=""
            for commit in $commits; do
              if git rev-parse "$commit^" >/dev/null 2>&1; then
                files+=$(git diff --name-only "$commit^" "$commit" | sed 's/^/- `/' | sed 's/$/`/')$'\n'
              else
                files+=$(git diff --name-only --root "$commit" | sed 's/^/- `/' | sed 's/$/`/')$'\n'
              fi
            done
            files=$(echo "$files" | grep -v '^$')
          else
            files=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.pull_request._links.commits.href }} | \
              jq -r '.[] | .sha' | xargs -I {} git diff --name-only {}^ {} | sed 's/^/- `/' | sed 's/$/`/')
          fi
          if [ -z "$files" ]; then
            files="- `Нет измененных файлов`"
          fi
          echo "Files detected: $files"
          echo "CHANGED_FILES<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Telegram Message
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            EVENT_TYPE="Пуш"
          else
            EVENT_TYPE="Мердж"
          fi
          echo "Debug CHANGED_FILES: ${{ steps.changed-files.outputs.CHANGED_FILES }}"
          # Экранируем обратные апострофы в CHANGED_FILES
          ESCAPED_FILES=$(echo "${{ steps.changed-files.outputs.CHANGED_FILES }}" | sed 's/`/\\`/g')
          MESSAGE="Событие: *${EVENT_TYPE}*\nРепозиторий: _${{ github.repository }}_\nАвтор: _${{ github.actor }}_\nВетка: _${{ github.ref_name }}_\nСообщение: _${{ github.event.commits[0].message || github.event.pull_request.title }}_\nИзмененные файлы:\n${ESCAPED_FILES}\n[Ссылка](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_TO }}" \
            -d message_thread_id="${{ secrets.TELEGRAM_THREAD_ID }}" \
            -d parse_mode="Markdown" \
            -d "text=${MESSAGE}"
