name: Telegram Notify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Changed Files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            commits=$(echo '${{ toJson(github.event.commits) }}' | jq -r '.[].id')
            files=""
            for commit in $commits; do
              if git rev-parse "$commit^" >/dev/null 2>&1; then
                files+=$(git diff --name-only "$commit^" "$commit" 2>/dev/null)$'\n'
              else
                files+=$(git diff --name-only --root "$commit" 2>/dev/null)$'\n'
              fi
            done
            files=$(echo "$files" | grep -v '^$')
          else
            files=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.pull_request._links.commits.href }} | \
              jq -r '.[] | .sha' | xargs -I {} git diff --name-only {}^ {} 2>/dev/null)
          fi
          if [ -z "$files" ]; then
            files="Нет измененных файлов"
          fi
          echo "Raw files detected: $files"
          echo "RAW_FILES<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Format Files for Telegram
        id: format-files
        run: |
          formatted_files=$(echo "${{ steps.changed-files.outputs.RAW_FILES }}" | sed "s|^|- [\0](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/\0)|" | grep -v '^$')
          if [ -z "$formatted_files" ]; then
            formatted_files="- Нет измененных файлов"
          fi
          echo "Formatted files: $formatted_files"
          echo "FORMATTED_FILES<<EOF" >> $GITHUB_OUTPUT
          echo "$formatted_files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Telegram Message
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            EVENT_TYPE="Пуш"
          else
            EVENT_TYPE="Мердж"
          fi
          echo "Debug FORMATTED_FILES: ${{ steps.format-files.outputs.FORMATTED_FILES }}"
          MESSAGE=$(printf "Событие: *%s*\nРепозиторий: _%s_\nАвтор: _%s_\nВетка: _%s_\nСообщение: _%s_\nИзмененные файлы:\n%s\n[Ссылка](https://github.com/%s/commit/%s)" \
            "$EVENT_TYPE" \
            "${{ github.repository }}" \
            "${{ github.actor }}" \
            "${{ github.ref_name }}" \
            "${{ github.event.commits[0].message || github.event.pull_request.title }}" \
            "${{ steps.format-files.outputs.FORMATTED_FILES }}" \
            "${{ github.repository }}" \
            "${{ github.sha }}")
          echo "Final message: $MESSAGE"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_TO }}" \
            -d message_thread_id="${{ secrets.TELEGRAM_THREAD_ID }}" \
            -d parse_mode="Markdown" \
            -d "text=$MESSAGE"
