name: Telegram Notify

on:
  push:
    branches:
      - main  # Укажите вашу главную ветку (main, master и т.д.)
  pull_request:
    branches:
      - main
    types: [closed]  # Уведомление только при мердже (closed + merged)

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Changed Files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            # Для пуша берем измененные файлы из последнего коммита
            if git rev-parse HEAD^ >/dev/null 2>&1; then
              files=$(git diff --name-only HEAD^ HEAD | sed 's/^/- /')
            else
              files=$(git diff --name-only --root HEAD | sed 's/^/- /')
            fi
          else
            # Для мерджа берем измененные файлы из pull request
            files=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.pull_request._links.commits.href }} | \
              jq -r '.[] | .sha' | xargs -I {} git diff --name-only {}^ {} | sort -u | sed 's/^/- /')
          fi
          # Если файлов нет, укажем "Нет измененных файлов"
          if [ -z "$files" ]; then
            files="- Нет измененных файлов"
          fi

          echo "Files detected: $files"  # Отладочный вывод
          
          # Экранируем символы для Telegram и сохраняем в переменную
          echo "CHANGED_FILES<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT


      - name: Send Telegram Message
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_TO }}" \
            -d message_thread_id="${{ secrets.TELEGRAM_THREAD_ID }}" \
            -d parse_mode="Markdown" \
            -d text="Событие: *${{ github.event_name == 'push' && 'Пуш' || 'Мердж' }}* \
                    \nРепозиторий: _${{ github.repository }}_ \
                    \nАвтор: _${{ github.actor }}_ \
                    \nВетка: _${{ github.ref_name }}_ \
                    \nСообщение: _${{ github.event.commits[0].message || github.event.pull_request.title }}_ \
                    \nИзмененные файлы:\n${{ steps.changed-files.outputs.CHANGED_FILES }} \
                    \n[Ссылка](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
