name: Telegram Notify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Changed Files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            commits=$(echo '${{ toJson(github.event.commits) }}' | jq -r '.[].id')
            files=""
            for commit in $commits; do
              if git rev-parse "$commit^" >/dev/null 2>&1; then
                files+=$(git diff --name-only "$commit^" "$commit" | sed 's/^/- /')$'\n'
              else
                files+=$(git diff --name-only --root "$commit" | sed 's/^/- /')$'\n'
              fi
            done
            files=$(echo "$files" | sort -u | grep -v '^$')
          else
            files=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.pull_request._links.commits.href }} | \
              jq -r '.[] | .sha' | xargs -I {} git diff --name-only {}^ {} | sort -u | sed 's/^/- /')
          fi
          if [ -z "$files" ]; then
            files="- Нет измененных файлов"
          fi
          echo "Files detected: $files"
          echo "CHANGED_FILES<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Telegram Message
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          # Определяем тип события в shell
          if [ "${{ github.event_name }}" = "push" ]; then
            EVENT_TYPE="Пуш"
          else
            EVENT_TYPE="Мердж"
          fi
          MESSAGE=$(cat <<EOF
Репозиторий: _${{ github.repository }}_
Автор: _${{ github.actor }}_
Ветка: _${{ github.ref_name }}_
Сообщение: _${{ github.event.commits[0].message || github.event.pull_request.title }}_
Измененные файлы:
${{ steps.changed-files.outputs.CHANGED_FILES }}
[Ссылка](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
EOF
          )
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_TO }}" \
            -d message_thread_id="${{ secrets.TELEGRAM_THREAD_ID }}" \
            -d parse_mode="Markdown" \
            -d "text=$MESSAGE"
